version: '3.3'

services:
    db:
        restart: always
        image: mysql/mysql-server:5.7.28
        container_name: mlflow_db
        expose:
            - "3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql

    web:
        restart: always
        build: ./mlflow
        image: larribas/mlflow:latest

    nginx:
        restart: always
        build: ./nginx
        image: nginx:alpine
        container_name: mlflow_nginx
        ports:
            - "80:80"
        depends_on:
            - web

volumes:
    dbdata:
    artifactroot: